hulilab/Models/DAL/Share.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace hulilab.Models.DAL
{
    public class Share:BaseObject
    {
        [Required]
        [DefaultValue(null)]
        public int? Author { get; set; }//对应member id
        [Required]
        [DisplayName("标题")]
        public string Title { get; set; }
        [DisplayName("概括")]
        public string Description { get; set; }
        [DisplayName("内容")]
        public string Content { get; set; }
        [DisplayName("文件类型")]
        [Description("1为海报,2为资料总结,3为软件，0为未分类")]
        [DefaultValue(null)]
        public int? Type { get; set; } //1为海报,2为资料总结,3为软件，0为未分类
    }
}

hulilab/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hulilab.Models.DAL;
using hulilab.Models.BLL;
using hulilab.Models.Common;

namespace hulilab.Controllers
{
    public class CommentController : Controller
    {
        //
        // GET: /Comment/

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 增加评论
        /// </summary>
        /// <param name="member"></param>
        /// <returns></returns>
        public ActionResult AddComment(Comment comment)
        {
            comment.SubmitDate = DateTime.Now;
            CommentService cs = new CommentService();
            if (cs.Add(comment))
            {
                return Content(string.Format(Constants.SUCCESSALERT, Url.Content("~/Share?shareId="+comment.ShareId)));
            }
            else
            {
                return Content(string.Format(Constants.FAILALERT, cs.ErrorMsg));
            }
        }
    }
}

hulilab/Controllers/ShareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hulilab.Models.DAL;
using hulilab.Models.BLL;
using hulilab.Models.Common;

namespace hulilab.Controllers
{
    public class ShareController : Controller
    {
        //
        // GET: /Share/

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 查看某一类型的所有共享资料
        /// </summary>
        /// <returns></returns>
        public ActionResult Shares()
        {
            return View();
        }

        /// <summary>
        /// 增加新的资料分享
        /// </summary>
        /// <param name="member"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddShare(Share share)
        {
            share.Content = HttpUtility.HtmlEncode(share.Content);
            ShareService ss = new ShareService();
            if (ss.Add(share))
            {
                return Content(string.Format(Constants.SUCCESSALERT, Url.Content("~/Admin/ShareManagement")));
            }
            else
            {
                return Content(string.Format(Constants.FAILALERT, ss.ErrorMsg));
            }
        }

        /// <summary>
        /// 编辑分享资料信息
        /// </summary>
        /// <param name="member"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditShare(Share share)
        {
            share.Content = HttpUtility.HtmlEncode(share.Content);
            ShareService ss = new ShareService();
            if (ss.Edit(share))
            {
                return Content(string.Format(Constants.SUCCESSALERT, Url.Content("~/Admin/EditShare?shareId="+share.ID)));
            }
            else
            {
                return Content(string.Format(Constants.FAILALERT, ss.ErrorMsg));
            }
        }

        /// <summary>
        /// 删除一个分享资料
        /// </summary>
        /// <param name="member"></param>
        /// <returns></returns>
        public ActionResult DeleteShare(int shareId)
        {
            ShareService ss = new ShareService();
            Share share = new Share();
            share.ID = shareId;
            if (ss.ClearShare(share))
            {
                return Content(string.Format(Constants.SUCCESSALERT, Url.Content("~/Admin/ShareManagement")));
            }
            else
            {
                return Content(string.Format(Constants.FAILALERT, ss.ErrorMsg));
            }
        }
    }
}

hulilab/Views/Share/Index.cshtml
@model Comment
@using hulilab.Models.BLL
@using hulilab.Models.DAL
@using hulilab.Models.Common
<div class="inner">
    @{
        int? shareId = StringHelper.ConvertObjectToInt(Request.Params["shareId"]);
        if (null != shareId && shareId > 0)
        {
            ShareService ss = new ShareService();
            Share share = new Share();
            share.ID = shareId;
            if (ss.Find(share))
            {
        <div class="block">
            <div class="blocktitle">
                <h3>
                    @share.Title</h3>
                <br />
                <span>@StringHelper.GetShareType(@share.Type, Language.ENU)</span>
            </div>
            <div class="blockcontent">
                <table>
                    <tr>
                        <td>@Html.Raw(StringHelper.convertStringLineBreakToHtmlFormat(share.Description))
                        </td>
                    </tr>
                    <tr>
                        <td>@Html.Raw(HttpUtility.HtmlDecode(share.Content))
                        </td>
                    </tr>
                </table>
                <div class="box">
                    <div class="boxtitle">
                        <h3>
                            Comments:
                        </h3>
                    </div>
                    <div class="boxcontent">
                        @{
                List<Comment> comments;
                CommentService cs = new CommentService();
                if (cs.LoadShareComments((int)shareId, out comments))
                {
                    if (comments.Count > 0)
                    {
                        foreach (Comment comment in comments)
                        {
                            <p>@Html.Raw(StringHelper.convertStringLineBreakToHtmlFormat(comment.Content))</p>
                   
                            <p style="text-align: right">
                                submitted on @comment.SubmitDate by @MemberService.GetUserName(comment.Author, Language.ENU)
                            </p>
                       
                        }
                    }
                    else
                    {
                            <p>
                                No comments yet.</p>
                    }
                }
                        }
                    </div>
                </div>
                <div class="box">
                    <div class="boxtitle">
                        <h3>
                            Add Comment:
                        </h3>
                    </div>
                    <div class="boxcontent">
                        @using (Html.BeginForm("AddComment", "Comment", FormMethod.Post, new { @class = "form-horizontal" }))
                        {

                            @Html.HiddenFor(model => model.ShareId, new { Value = shareId })
                            @Html.HiddenFor(model => model.Author, new { Value = StringHelper.ConvertObjectToInt(Session["userId"]) })
                            <div class="editor-field">
                                <p>
                                    @Html.TextAreaFor(model => model.Content, new { @class = "edittextarea" })
                                    @Html.ValidationMessageFor(model => model.Content)
                                </p>
                            </div>
                            <p>
                                <input type="submit" value="Send" class="btn" />
                            </p>
                        }
                    </div>
                </div>
            </div>
        </div>
            }
            else
            {
        <p>@ss.ErrorMsg</p>
            }
        }
        else
        {
        <p>
            No such share.</p>
        }
    }
</div>

hulilab/Views/Share/Shares.cshtml
@using hulilab.Models.DAL
@using hulilab.Models.BLL
@using hulilab.Models.Common
<div class="inner">
    @{
        int? userId = StringHelper.ConvertObjectToInt(Session["userId"]);

        ShareService ss = new ShareService();
        List<Share> shares;
        if (ss.LoadAll(out shares))
        {
            foreach (var typeShares in shares.GroupBy(p => p.Type))
            {
        <div class="block">
            <div class="blocktitle">
                @if (!string.IsNullOrEmpty(StringHelper.GetShareType(typeShares.Key, Language.ENU)))
                {
                    <h3>
                        @StringHelper.GetShareType(typeShares.Key, Language.ENU)
                    </h3>
                }
                else
                {
                    <h3>
                        Others</h3>
                }
            </div>
            <div class="blockcontent">
                @if (shares.Count > 0)
                {
                    <table class="full">
                        @foreach (Share share in typeShares)
                        {
                            <tr>
                                <td>
                                    @Html.ActionLink(share.Title, "Index", "Share", new { shareId = share.ID }, null)
                                </td>
                            </tr>
                        }
                    </table>
                }
                else
                {
                    <p>
                        Nothing is shared yet.</p>
                }
            </div>
        </div>
            }
        }
        else
        {
        <p>@ss.ErrorMsg</p>
        }
    }
</div>